Kits:
  Warrior:
    Armor:
      chainmail_helmet: 1
      warrior_chestplate: 1
      warrior_leggings: 1
      chainmail_boots: 1
    Items:
      baked_potato: 16
      iron_sword: 1

  Archer:
    Armor:
      chainmail_helmet: 1
      chainmail_chestplate: 1
      chainmail_leggings: 1
      chainmail_boots: 1
    Items:
      baked_potato: 16
      archer_bow: 1
      arrow: 1

  Rusher:
    Armor:
      leather_helmet: 1
      chainmail_chestplate: 1
      chainmail_leggings: 1
      leather_boots: 1
    Items:
      baked_potato: 16
      rusher_sword: 1
      ender_pearl: 2
      stone: 64

  Alchimist:
    Armor:
      chainmail_helmet: 1
      chainmail_chestplate: 1
      chainmail_leggings: 1
      chainmail_boots: 1
    Items:
      baked_potato: 16

  BallsBreaker:
    Armor:
      ballsbreaker_helmet: 1
      ballsbreaker_chestplate: 1
      ballsbreaker_leggings: 1
      ballsbreaker_boots: 1
    Items:
      baked_potato: 16
      ballsbreaker_fishing_rod: 1








PersonnalItems:
  archer_bow:
    item: bow
    enchantment:
       ARROW_DAMAGE: 1000
       ARROW_INFINITE: 1
       DURABILITY: 10

  warrior_chestplate:
    item: iron_chestplate
    enchantment:
      PROTECTION_ENVIRONMENTAL: 1
      DURABILITY: 5
  warrior_leggings:
    item: iron_leggings
    enchantment:
      PROTECTION_ENVIRONMENTAL: 1
      DURABILITY: 5

  rusher_sword:
    item: stone_sword
    enchantment:
      DAMAGE_ALL: 1
      DURABILITY: 5
  
  ballsbreaker_helmet:
    item: leather_helmet
    enchantment:
      THORNS: 2
      DURABILITY: 100
  ballsbreaker_chestplate:
    item: leather_chestplate
    enchantment:
      THORNS: 2
      DURABILITY: 100
  ballsbreaker_leggings:
    item: leather_leggings
    enchantment:
      THORNS: 2
      DURABILITY: 100
  ballsbreaker_boots:
    item: leather_boots
    enchantment:
      THORNS: 2
      DURABILITY: 100
  ballsbreaker_fishing_rod:
    item: fishing_rod
    enchantment:
      KNOCKBACK: 5
      ARROW_KNOCKBACK: 5



Location:
  Red:
    Pool:
      X:
      Y:
      Z:
      X2:
      Y2:
      Z2:
    Spawn:
      X:
      Y:
      Z:
  Blue:
    Pool:
      X:
      Y:
      Z:
      X2:
      Y2:
      Z2:
    Spawn:
      X:
      Y:
      Z:
  ItemSpawn:
    Iron_Ingot: 1
    