Kits:
   Default:
      Armor:
         leather_helmet: 1
         leather_chestplate: 1
         leather_leggings: 1
         leather_boots: 1
      Items:
         potatoes: 16
   
   
      