Kits:
   Default:
      Armor:
         leather_helmet: 1
         leather_chestplate: 1
         leather_leggings: 1
         leather_boots: 1
      Items:
         potatoes: 16
   
Data:
   Objects:
      Kits:
         ID: 0
         affiliated_object: diamond_sword
         name: Kits
         description: Ouvre le menu des kits
      Jeux:
         ID: 1
         affiliated_object: compass
         name: Jeux
         description: Ouvre le menu des jeux
      
